import bcrypt from 'bcrypt'; import pool from './config/db.js';
const usuarios=[['Administrador','General','Sistema','admin','admin@kunibo.com','Admin123!','admin'],['Cajero','Demostración','Sistema','cajero','cajero@kunibo.com','Cajero123!','cajero']];
const productos=['Espresso','Americano','Capuchino','Latte','Moca','Té chai','Chocolate caliente','Frappé','Cold brew','Pan dulce'];
const client=await pool.connect();
try{await client.query('BEGIN');
 for(const [n,ap,am,u,email,password,rol] of usuarios){const hash=await bcrypt.hash(password,10);await client.query(`INSERT INTO usuarios(nombre_us,ap_us,am_us,direccion,telefono,usuario,email,password,rol) SELECT $1,$2,$3,'Cafetería Kunibo','6180000000',$4,$5,$6,$7 WHERE NOT EXISTS(SELECT 1 FROM usuarios WHERE usuario=$4)`,[n,ap,am,u,email,hash,rol]);}
 await client.query(`INSERT INTO proveedor(nombre_pv,direccion_pv,telefono_pv) SELECT 'Distribuidora Kunibo','Zona Centro','6181234567' WHERE NOT EXISTS(SELECT 1 FROM proveedor WHERE nombre_pv='Distribuidora Kunibo')`);
 const pv=(await client.query(`SELECT id_proveedor FROM proveedor ORDER BY CASE WHEN nombre_pv='Distribuidora Kunibo' THEN 0 ELSE 1 END,id_proveedor LIMIT 1`)).rows[0].id_proveedor;
 for(let i=0;i<productos.length;i++){const codigo=`DEMO-${String(i+1).padStart(3,'0')}`;await client.query(`INSERT INTO productos(codigo,nombre_producto,precio_compra,precio_venta,existencia,stock_minimo,iva,id_proveedor) SELECT $1,$2,$3,$4,30,10,16,$5 WHERE NOT EXISTS(SELECT 1 FROM productos WHERE codigo=$1)`,[codigo,productos[i],20+i,35+i*3,pv]);}
 const clientes=[['Ana Martínez','MARA900101AA1','Centro','6181111111'],['Luis Hernández','HEHL880202BB2','Col. Jardines','6182222222'],['Sofía Ramírez','RARS950303CC3','Col. Victoria','6183333333']];
 for(const c of clientes)await client.query(`INSERT INTO cliente(nombre_cliente,"RFC",domicilio,telefono) SELECT $1,$2,$3,$4 WHERE NOT EXISTS(SELECT 1 FROM cliente WHERE "RFC"=$2)`,c);
 const totalVentas=Number((await client.query('SELECT COUNT(*) AS n FROM venta')).rows[0].n);
 if(!totalVentas){const cajero=(await client.query(`SELECT id_usuario FROM usuarios WHERE usuario='cajero'`)).rows[0];const ps=(await client.query(`SELECT id_producto,precio_venta,iva FROM productos ORDER BY id_producto LIMIT 3`)).rows;for(let i=0;i<3;i++){const p=ps[i%ps.length],sub=Number(p.precio_venta)*(i+1),iva=sub*Number(p.iva||0)/100,total=sub+iva;const v=(await client.query(`INSERT INTO venta(fecha_v,id_usuario_v,subtotal,iva_total,propina,descuento,total,metodo_pago,tipo_venta,monto_recibido,cambio,estado) VALUES(NOW()-($1||' hours')::interval,$2,$3,$4,0,0,$5,$6,'llevar',$7,$8,'COMPLETADA') RETURNING id_venta`,[i*2,cajero.id_usuario,sub,iva,total,i%2?'tarjeta':'efectivo',i%2?null:total,i%2?null:0])).rows[0];await client.query('INSERT INTO detalle_venta(id_venta_dv,id_producto_dv,precio_s_dv,cantidad) VALUES($1,$2,$3,$4)',[v.id_venta,p.id_producto,p.precio_venta,i+1]);await client.query('UPDATE productos SET existencia=existencia-$1 WHERE id_producto=$2',[i+1,p.id_producto]);}}
 await client.query('COMMIT');console.log('Datos demo creados. Admin: admin / Admin123! | Cajero: cajero / Cajero123!');
}catch(e){await client.query('ROLLBACK');console.error(e);process.exitCode=1;}finally{client.release();await pool.end();}
